import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import FooterNav from "@/components/FooterNav";
import JsonLdWebPage from "@/components/JsonLdWebPage";

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (typeof process.env.VERCEL_URL === "string"
    ? `https://${process.env.VERCEL_URL}`
    : "https://cvengine.space");

export const metadata: Metadata = {
  title: "Markdown to Word (.docx) Converter — Free CV Download",
  description:
    "Convert Markdown (.md) to a Word (.docx) CV or resume instantly. Paste or upload your .md file, preview live, download .docx. Free — no signup required.",
  alternates: { canonical: `${siteUrl}/markdown-to-word` },
  keywords: [
    "markdown to word",
    "markdown to docx",
    "md to word",
    "md to docx",
    ".md to word",
    "md file to docx",
    "markdown to word converter",
    "convert markdown to word",
    "markdown resume word",
    "markdown CV docx",
    "markdown to microsoft word",
  ],
  openGraph: {
    title: "Markdown to Word (.docx) Converter | CVEngine",
    description:
      "Convert a .md file to a Word (.docx) CV. Paste or upload Markdown, preview live, download .docx instantly. Free — no signup.",
    url: `${siteUrl}/markdown-to-word`,
  },
  twitter: {
    card: "summary_large_image",
    title: "Markdown to Word (.docx) Converter | CVEngine",
    description:
      "Convert Markdown to Word (.docx) CV. Free — no signup.",
  },
};

const HOW_IT_WORKS = [
  {
    n: "1",
    title: "Paste or upload your .md file",
    body: "Open the CV builder and paste your Markdown content, or click Upload .md to load a file from your computer. The editor accepts standard Markdown syntax.",
  },
  {
    n: "2",
    title: "Preview your CV in real time",
    body: "A live preview renders your CV as you type, so you can verify headings, bullet points, and formatting before downloading.",
  },
  {
    n: "3",
    title: "Download Word (.docx)",
    body: 'Click "Download Word" to convert your Markdown to a .docx file instantly. The Word document preserves headings (H1–H3), bullet lists, and bold text — ready to submit to recruiters or edit further in Microsoft Word or Google Docs.',
  },
];

const FAQ = [
  {
    q: "What Markdown elements are converted to Word?",
    a: "CVEngine converts: # H1 → Heading 1, ## H2 → Heading 2, ### H3 → Heading 3, - bullet points → Word bullet list, and **bold** → bold text. Links and plain paragraphs are also supported.",
  },
  {
    q: "Is the Markdown to Word conversion free?",
    a: "Yes — completely free. No account, no signup, no payment. Paste your .md content and download the .docx file immediately.",
  },
  {
    q: "Can I open the .docx file in Google Docs?",
    a: "Yes. The .docx file generated by CVEngine is compatible with Microsoft Word, Google Docs, LibreOffice, and any other application that reads the standard Word format.",
  },
  {
    q: "Can I also download a PDF from the same Markdown?",
    a: "Yes. The CV builder has both a Download PDF and a Download Word button. You can download either format (or both) from your Markdown content without re-entering anything.",
  },
  {
    q: "Why would I want a Word file instead of PDF?",
    a: "Some recruiters or HR systems specifically request Word (.docx) files because they can parse and edit them more easily. Having both PDF and Word versions from the same Markdown source is the safest approach for job applications.",
  },
];

export default function MarkdownToWordPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Markdown to Word (.docx) Converter — Free CV Download",
    description:
      "Convert Markdown (.md) to a Word (.docx) CV or resume instantly. Free — no signup.",
    url: `${siteUrl}/markdown-to-word`,
  };

  const jsonLdFaq = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };

  return (
    <div className="min-h-screen flex flex-col bg-[var(--background)]">
      <JsonLdWebPage data={jsonLd} />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdFaq) }}
      />
      <SiteHeader />

      <main id="main-content" className="flex-1 max-w-3xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-10">

        {/* Hero */}
        <div className="mb-10 text-center">
          <h1 className="text-3xl sm:text-4xl font-bold text-[var(--foreground)] tracking-tight mb-3">
            Markdown to Word (.docx)
          </h1>
          <p className="text-[var(--muted)] text-base max-w-xl mx-auto mb-2">
            Convert a <code className="font-[family-name:var(--font-geist-mono)] text-sm bg-[var(--card-border)]/60 px-1.5 py-0.5 rounded">.md</code> file to a Word <code className="font-[family-name:var(--font-geist-mono)] text-sm bg-[var(--card-border)]/60 px-1.5 py-0.5 rounded">.docx</code> CV or resume. Free — no signup.
          </p>
          <p className="text-[var(--muted)] text-sm max-w-xl mx-auto mb-8">
            Paste your Markdown content, preview live, and download a Word document compatible with Microsoft Word, Google Docs, and LibreOffice.
          </p>
          <Link
            href="/cv"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-2xl text-lg font-semibold text-white bg-[var(--accent)] hover:bg-[var(--accent-hover)] shadow-lg hover:shadow-xl transition-all focus:outline-none focus:ring-2 focus:ring-[var(--accent)] focus:ring-offset-2"
          >
            Convert Markdown to Word
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </Link>
        </div>

        {/* How it works */}
        <section className="mb-12">
          <h2 className="text-xl font-bold text-[var(--foreground)] mb-6">
            How to convert Markdown to Word
          </h2>
          <div className="space-y-6">
            {HOW_IT_WORKS.map((step) => (
              <div key={step.n} className="flex gap-4">
                <div className="shrink-0 w-10 h-10 rounded-xl bg-[var(--accent)]/10 text-[var(--accent)] flex items-center justify-center font-bold text-lg">
                  {step.n}
                </div>
                <div>
                  <h3 className="text-base font-semibold text-[var(--foreground)] mb-1">{step.title}</h3>
                  <p className="text-sm text-[var(--muted)] leading-relaxed">{step.body}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* PDF vs Word */}
        <section className="mb-12 rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-6 sm:p-8 shadow-sm">
          <h2 className="text-lg font-semibold text-[var(--foreground)] mb-3">
            PDF vs Word — which should I use?
          </h2>
          <div className="grid sm:grid-cols-2 gap-4 text-sm">
            <div>
              <p className="font-semibold text-[var(--foreground)] mb-2">Use PDF when:</p>
              <ul className="list-disc pl-4 space-y-1 text-[var(--muted)]">
                <li>Applying through an online portal that accepts PDF</li>
                <li>You want to preserve your exact formatting</li>
                <li>The job posting doesn&apos;t specify a format</li>
                <li>You&apos;re sending directly to a recruiter by email</li>
              </ul>
            </div>
            <div>
              <p className="font-semibold text-[var(--foreground)] mb-2">Use Word (.docx) when:</p>
              <ul className="list-disc pl-4 space-y-1 text-[var(--muted)]">
                <li>The recruiter or system explicitly asks for Word</li>
                <li>You want to allow editing after submission</li>
                <li>An ATS system requires .docx input</li>
                <li>You&apos;re sharing with someone who needs to add comments</li>
              </ul>
            </div>
          </div>
          <p className="text-xs text-[var(--muted)] mt-4">
            CVEngine generates both from the same Markdown — download whichever you need.
          </p>
        </section>

        {/* What gets converted */}
        <section className="mb-12">
          <h2 className="text-lg font-semibold text-[var(--foreground)] mb-4">
            What Markdown converts to in Word
          </h2>
          <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] overflow-hidden">
            {[
              ["# Your Name", "Word Heading 1"],
              ["## Experience", "Word Heading 2"],
              ["### Job Title", "Word Heading 3"],
              ["- Bullet point", "Word bullet list"],
              ["**Bold text**", "Bold"],
              ["Plain paragraph", "Normal paragraph"],
            ].map(([md, word], i) => (
              <div
                key={md}
                className={`flex items-center gap-4 px-4 py-3 text-sm ${
                  i % 2 === 0 ? "bg-[var(--background)]/40" : ""
                }`}
              >
                <code className="font-[family-name:var(--font-geist-mono)] text-[var(--accent)] w-40 shrink-0">
                  {md}
                </code>
                <span className="text-[var(--muted)]">→ {word}</span>
              </div>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section className="mb-12">
          <h2 className="text-lg font-semibold text-[var(--foreground)] mb-4">
            Frequently asked questions
          </h2>
          <div className="space-y-4">
            {FAQ.map(({ q, a }) => (
              <div key={q} className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-5">
                <h3 className="text-sm font-semibold text-[var(--foreground)] mb-2">{q}</h3>
                <p className="text-sm text-[var(--muted)] leading-relaxed">{a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <div className="text-center mb-10">
          <p className="text-sm text-[var(--muted)] mb-4">
            Also need a PDF?{" "}
            <Link href="/markdown-to-pdf" className="text-[var(--accent)] hover:underline">
              Markdown to PDF →
            </Link>
          </p>
          <Link
            href="/cv"
            className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl text-base font-semibold text-white bg-[var(--accent)] hover:bg-[var(--accent-hover)] shadow-md hover:shadow-lg transition-all"
          >
            Open Markdown to Word converter
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </Link>
        </div>

        <FooterNav />
      </main>
    </div>
  );
}
