"use client";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import FooterNav from "@/components/FooterNav";
import JsonLdWebPage from "@/components/JsonLdWebPage";

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (typeof process.env.VERCEL_URL === "string"
    ? `https://${process.env.VERCEL_URL}`
    : "https://cvengine.space");

const HOW_IT_WORKS = [
  {
    n: "1",
    title: "Paste or upload your .md file",
    body: "Open the CV builder and paste your Markdown content, or click Upload .md to load a file from your computer. The editor accepts standard Markdown syntax.",
  },
  {
    n: "2",
    title: "Preview your CV in real time",
    body: "A live preview renders your CV as you type, so you can verify headings, bullet points, and formatting before downloading.",
  },
  {
    n: "3",
    title: "Download Word (.docx)",
    body: 'Click "Download Word" to convert your Markdown to a .docx file instantly. The Word document preserves headings (H1â€“H3), bullet lists, and bold text â€” ready to submit to recruiters or edit further in Microsoft Word or Google Docs.',
  },
];

const FAQ = [
  {
    q: "What Markdown elements are converted to Word?",
    a: "CVEngine converts: # H1 â†’ Heading 1, ## H2 â†’ Heading 2, ### H3 â†’ Heading 3, - bullet points â†’ Word bullet list, and **bold** â†’ bold text. Links and plain paragraphs are also supported.",
  },
  {
    q: "Is the Markdown to Word conversion free?",
    a: "Yes â€” completely free. No account, no signup, no payment. Paste your .md content and download the .docx file immediately.",
  },
  {
    q: "Can I open the .docx file in Google Docs?",
    a: "Yes. The .docx file generated by CVEngine is compatible with Microsoft Word, Google Docs, LibreOffice, and any other application that reads the standard Word format.",
  },
  {
    q: "Can I also download a PDF from the same Markdown?",
    a: "Yes. The CV builder has both a Download PDF and a Download Word button. You can download either format (or both) from your Markdown content without re-entering anything.",
  },
  {
    q: "Why would I want a Word file instead of PDF?",
    a: "Some recruiters or HR systems specifically request Word (.docx) files because they can parse and edit them more easily. Having both PDF and Word versions from the same Markdown source is the safest approach for job applications.",
  },
];

export default function MarkdownToWordPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Markdown to Word (.docx) Converter â€” Free CV Download",
    description:
      "Convert Markdown (.md) to a Word (.docx) CV or resume instantly. Free â€” no signup.",
    url: `${siteUrl}/markdown-to-word`,
  };

  const jsonLdFaq = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };

  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column", background: "var(--bg)" }}>
      <JsonLdWebPage data={jsonLd} />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdFaq) }}
      />
      <SiteHeader />

      <main style={{ flex: 1, maxWidth: 640, width: "100%", margin: "0 auto", padding: "48px 24px 64px" }} className="anim-fade-in-up">
        {/* Hero */}
        <div style={{ textAlign: "center", marginBottom: 48 }}>
          <h1 style={{ fontSize: 28, fontWeight: 800, color: "var(--text)", letterSpacing: "-0.02em", margin: "0 0 12px" }}>
            Markdown to Word
          </h1>
          <p style={{ fontSize: 14, color: "var(--text-muted)", lineHeight: 1.6, maxWidth: 520, margin: "0 auto 24px" }}>
            Convert your <code style={{ fontFamily: "ui-monospace, monospace", fontSize: 12, background: "var(--surface-raised)", border: "1px solid var(--border)", padding: "2px 4px", borderRadius: 4 }}>.md</code> file directly to a clean Word <code style={{ fontFamily: "ui-monospace, monospace", fontSize: 12, background: "var(--surface-raised)", border: "1px solid var(--border)", padding: "2px 4px", borderRadius: 4 }}>.docx</code> file. Free, client-side, and private.
          </p>
          <Link
            href="/cv"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              padding: "8px 20px",
              borderRadius: 6,
              fontSize: 14,
              fontWeight: 600,
              color: "#ffffff",
              background: "var(--accent)",
              textDecoration: "none",
              transition: "background 0.15s",
            }}
            onMouseEnter={(e) => (e.currentTarget as HTMLElement).style.background = "var(--accent-hover)"}
            onMouseLeave={(e) => (e.currentTarget as HTMLElement).style.background = "var(--accent)"}
          >
            Start Building Free
            <svg width={14} height={14} fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </Link>
        </div>

        {/* How it works */}
        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "var(--text)", margin: "0 0 20px" }}>
            How to Convert Markdown to Word
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            {HOW_IT_WORKS.map((step) => (
              <div key={step.n} style={{ display: "flex", gap: 16 }}>
                <div style={{
                  flexShrink: 0,
                  width: 32,
                  height: 32,
                  borderRadius: 6,
                  background: "var(--accent-bg)",
                  color: "var(--accent-text)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontWeight: 700,
                  fontSize: 14,
                }}>
                  {step.n}
                </div>
                <div>
                  <h3 style={{ fontSize: 14, fontWeight: 650, color: "var(--text)", margin: "0 0 4px" }}>{step.title}</h3>
                  <p style={{ fontSize: 13, color: "var(--text-muted)", lineHeight: 1.5, margin: 0 }}>{step.body}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* PDF vs Word */}
        <section style={{ border: "1px solid var(--border)", borderRadius: 8, background: "var(--surface)", padding: 20, marginBottom: 48 }}>
          <h2 style={{ fontSize: 14, fontWeight: 700, color: "var(--text)", margin: "0 0 12px" }}>
            PDF vs Word â€” Which should I use?
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 16 }} className="sm:grid-cols-2">
            <div>
              <p style={{ fontSize: 13, fontWeight: 700, color: "var(--text)", margin: "0 0 6px" }}>Use PDF when:</p>
              <ul style={{ paddingLeft: 16, listStyleType: "disc", fontSize: 12.5, color: "var(--text-muted)", display: "flex", flexDirection: "column", gap: 4 }}>
                <li>Applying through portals that parse PDFs.</li>
                <li>You want to preserve strict layout formatting.</li>
                <li>The job posting doesn&apos;t specify a format.</li>
              </ul>
            </div>
            <div>
              <p style={{ fontSize: 13, fontWeight: 700, color: "var(--text)", margin: "0 0 6px" }}>Use Word (.docx) when:</p>
              <ul style={{ paddingLeft: 16, listStyleType: "disc", fontSize: 12.5, color: "var(--text-muted)", display: "flex", flexDirection: "column", gap: 4 }}>
                <li>Recruiters request Word files.</li>
                <li>You want to edit the file further locally.</li>
                <li>An ATS system recommends docx format.</li>
              </ul>
            </div>
          </div>
        </section>

        {/* What gets converted */}
        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "var(--text)", margin: "0 0 16px" }}>
            Conversion Map
          </h2>
          <div style={{ border: "1px solid var(--border)", borderRadius: 8, overflow: "hidden", background: "var(--surface)" }}>
            {[
              ["# Your Name", "Word Heading 1"],
              ["## Experience", "Word Heading 2"],
              ["### Job Title", "Word Heading 3"],
              ["- Bullet point", "Word bullet list"],
              ["**Bold text**", "Bold"],
              ["Plain paragraph", "Normal paragraph"],
            ].map(([md, word], i) => (
              <div
                key={md}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 16,
                  padding: "10px 16px",
                  fontSize: 13,
                  background: i % 2 === 0 ? "var(--surface-raised)" : "transparent",
                  borderBottom: i < 5 ? "1px solid var(--border)" : "none",
                }}
              >
                <code style={{ fontFamily: "ui-monospace, monospace", color: "var(--accent)", width: 140, flexShrink: 0 }}>
                  {md}
                </code>
                <span style={{ color: "var(--text-muted)" }}>â†’ {word}</span>
              </div>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "var(--text)", margin: "0 0 16px" }}>
            Frequently Asked Questions
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            {FAQ.map(({ q, a }) => (
              <div key={q} style={{ border: "1px solid var(--border)", borderRadius: 8, background: "var(--surface)", padding: 16 }}>
                <h3 style={{ fontSize: 13.5, fontWeight: 700, color: "var(--text)", margin: "0 0 8px" }}>{q}</h3>
                <p style={{ fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.5, margin: 0 }}>{a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <div style={{ textAlign: "center", borderTop: "1px solid var(--border)", paddingTop: 32 }}>
          <p style={{ fontSize: 13, color: "var(--text-muted)", margin: "0 0 16px" }}>
            Also need a PDF?{" "}
            <Link href="/markdown-to-pdf" style={{ color: "var(--accent)", textDecoration: "underline" }}>
              Markdown to PDF â†’
            </Link>
          </p>
          <Link
            href="/cv"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              padding: "8px 20px",
              borderRadius: 6,
              fontSize: 14,
              fontWeight: 600,
              color: "#ffffff",
              background: "var(--accent)",
              textDecoration: "none",
              transition: "background 0.15s",
            }}
            onMouseEnter={(e) => (e.currentTarget as HTMLElement).style.background = "var(--accent-hover)"}
            onMouseLeave={(e) => (e.currentTarget as HTMLElement).style.background = "var(--accent)"}
          >
            Open CV Builder
          </Link>
        </div>

        <footer style={{ borderTop: "1px solid var(--border)", padding: "24px 0", background: "var(--surface)", marginTop: 48 }}>
          <FooterNav />
        </footer>
      </main>
    </div>
  );
}